services:
  - type: web
    name: logistica-catraia
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGSSL
        value: "true"
